### PR TITLE
Accept Joi schemas and strings in unknown type assertion

### PR DESCRIPTION
**Pull request by vamcs**
As a follow-up to https://github.com/mrjono1/joi-to-typescript/issues/168, I've extended the unknown type assertion to accept Joi schemas and updated and added a few fixes to the README.

So now, complex types will be properly reproduced when creating complex `Record`s and if `.pattern(Joi.string(), ...)` is used, the Joi validation will still be taken into account, but the generated type will be more accurate.

### CODE REVIEW

**Comment by mrjono1** [comment]
I have used your commits in this MR https://github.com/mrjono1/joi-to-typescript/pull/181 to fix up the test coverage

**Comment by mrjono1** [comment]
thankyou for all the little fixes as well

**Comment by mrjono1** [comment]
Released under https://github.com/mrjono1/joi-to-typescript/releases/tag/2.4.0

**Comment by vamcs** [comment]
@mrjono1 amazing, thanks a lot for merging this!

**Pull request merged**
