### PR TITLE
Fixes CJS usages

### PR DESCRIPTION
**Pull request by LukeShay**
Removed `"type": "module"` from `package.json` to fix the CJS usage.

I also added an example for ESM and CJS.

### CODE REVIEW

**Comment by mrjono1** [comment]
Great job with the examples

**Comment by LukeShay** [comment]
@mrjono1 Could we get a release of this so it works with CJS projects?

**Comment by mrjono1** [comment]
Can do, I'll try to get it out in about 12 hours

**Comment by mrjono1** [comment]
released under https://github.com/mrjono1/joi-to-typescript/releases/tag/3.0.3

**Pull request merged**
